use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=skills/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_skills.rs");

    let skills_dir = Path::new("skills");
    let mut entries = Vec::new();

    if skills_dir.is_dir() {
        for entry in fs::read_dir(skills_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let skill_file = path.join("SKILL.md");
            if !skill_file.exists() {
                continue;
            }
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let content = fs::read_to_string(&skill_file).unwrap_or_default();

            // Parse YAML frontmatter for description
            let description = extract_frontmatter_field(&content, "description:")
                .unwrap_or_else(|| format!("Skill: {name}"));

            entries.push((name, description, skill_file.display().to_string()));
        }
    }

    // Sort by name for deterministic output
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate Rust source
    let mut code = String::from(
        "// Auto-generated by build.rs — do not edit manually.\n\
         // To add a skill: create skills/<name>/SKILL.md and rebuild.\n\n",
    );

    code.push_str("pub fn all() -> Vec<Skill> {\n");
    code.push_str("    vec![\n");
    for (name, desc, _path) in &entries {
        code.push_str(&format!(
            "        Skill {{\n\
             name: \"{name}\",\n\
             description: \"{desc}\",\n\
             content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/skills/{name}/SKILL.md\")),\n\
         }},\n"
        ));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    // Generate find function
    code.push_str(
        "pub fn find(name: &str) -> Option<Skill> {\n\
         all().into_iter().find(|s| s.name == name)\n\
         }\n",
    );

    fs::write(&dest_path, &code).unwrap();
    println!(
        "cargo::warning=Generated embedded_skills.rs with {} skills",
        entries.len()
    );
}

fn extract_frontmatter_field(content: &str, field: &str) -> Option<String> {
    let lines: Vec<&str> = content.lines().collect();
    if lines.first()?.trim() != "---" {
        return None;
    }
    for line in &lines[1..] {
        let trimmed = line.trim();
        if trimmed == "---" {
            break;
        }
        if let Some(value) = trimmed.strip_prefix(field) {
            let val = value.trim().trim_matches('"').trim_matches('\'');
            if !val.is_empty() {
                return Some(val.to_string());
            }
        }
    }
    None
}
