//! 构建脚本：自动构建 web 前端（npm run build）并把 dist 产物嵌入二进制。
//!
//! - `cargo build -p mink-server` 时自动执行 `npm run build`（web/ 目录）
//! - 遍历 dist 产物，生成 `OUT_DIR/assets.rs`（路径 → include_str! 内容表）
//! - npm 缺失/失败默认中止；MINK_SERVER_ALLOW_EMPTY_WEB=1 才允许空 UI

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_dir(&from, &to)?;
        } else {
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}

fn walk_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                out.extend(walk_files(&p));
            } else {
                out.push(p);
            }
        }
    }
    out
}

fn main() {
    println!("cargo:rerun-if-changed=web/src");
    println!("cargo:rerun-if-changed=web/index.html");
    println!("cargo:rerun-if-changed=web/package.json");

    // ── 版本溯源：嵌入 git commit hash（与 mink-cli/build.rs 同一协议）──
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let git_dir = manifest.join("../../.git");
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
    println!(
        "cargo:rerun-if-changed={}",
        git_dir.join("refs/heads/main").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        git_dir.join("packed-refs").display()
    );
    println!("cargo:rerun-if-env-changed=MINK_GIT_HASH");
    println!("cargo:rerun-if-env-changed=MINK_SERVER_ALLOW_EMPTY_WEB");
    let hash = match env::var("MINK_GIT_HASH") {
        Ok(value) if !value.trim().is_empty() => value.trim().to_string(),
        _ => git_short_hash()
            .map(|hash| {
                if working_tree_dirty() {
                    format!("{hash}-dirty")
                } else {
                    hash
                }
            })
            .unwrap_or_default(),
    };
    println!("cargo:rustc-env=MINK_GIT_HASH={hash}");
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let web_dir = manifest.join("web");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // 1. 自动构建前端（增量：npm 自身缓存，~100-200ms）
    let npm_ok = Command::new("npm")
        .args(["run", "build"])
        .current_dir(&web_dir)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !npm_ok {
        if env::var("MINK_SERVER_ALLOW_EMPTY_WEB").as_deref() != Ok("1") {
            panic!(
                "`npm run build` failed in {}; set MINK_SERVER_ALLOW_EMPTY_WEB=1 only for explicit headless builds",
                web_dir.display()
            );
        }
        eprintln!("[build.rs] warning: building without embedded web UI by explicit opt-in");
    }

    // 2. 复制 dist → OUT_DIR/assets（include_str! 需要编译期路径）
    let dist = web_dir.join("dist");
    let out_assets = out_dir.join("assets");
    let _ = fs::remove_dir_all(&out_assets);
    if dist.join("index.html").exists() {
        if let Err(e) = copy_dir(&dist, &out_assets) {
            eprintln!("[build.rs] warning: failed to copy dist: {e}");
        }
    } else if env::var("MINK_SERVER_ALLOW_EMPTY_WEB").as_deref() != Ok("1") {
        panic!("web build did not produce dist/index.html");
    }

    // 3. 生成 assets.rs（rel_path → include_str!(absolute))
    let mut entries = Vec::new();
    for file in walk_files(&out_assets) {
        let rel = file
            .strip_prefix(&out_assets)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        let abs = file.to_string_lossy().replace('\\', "\\\\");
        entries.push(format!("    ({:?}, include_str!({:?})),", rel, abs));
    }
    let asset_rs = format!(
        "// @generated by build.rs — web dist 嵌入清单（勿手改）\npub static FILES: &[(&str, &str)] = &[\n{}\n];\n",
        entries.join("\n")
    );
    fs::write(out_dir.join("assets.rs"), asset_rs).expect("write assets.rs");
    println!("[build.rs] embedded {} web assets", entries.len());
}

fn git_short_hash() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let hash = String::from_utf8_lossy(&output.stdout).trim().to_string();
    (!hash.is_empty()).then_some(hash)
}

/// Dirty = any tracked file changed (untracked build artifacts excluded).
fn working_tree_dirty() -> bool {
    Command::new("git")
        .args(["status", "--porcelain", "--untracked-files=no"])
        .output()
        .ok()
        .is_some_and(|output| output.status.success() && !output.stdout.is_empty())
}
