pub const TOOLS_JSON: &str = include_str!("assets/tools.json");

/// Embedded skills built into the binary.
/// Auto-generated by build.rs from the `skills/` directory.
/// To add a skill: create `skills/<name>/SKILL.md` and rebuild — no Rust code changes needed.
pub mod embedded_skills {
    pub struct Skill {
        pub name: &'static str,
        pub description: &'static str,
        pub content: &'static str,
    }

    // Include the auto-generated skill registry (defines pub fn all() and pub fn find)
    include!(concat!(env!("OUT_DIR"), "/embedded_skills.rs"));
}
